# Generated by Django 5.1.4 on 2025-01-09 05:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingAdress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Shipping_full_name', models.CharField(max_length=255)),
                ('Shipping_email', models.EmailField(max_length=255)),
                ('Shipping_addresse', models.CharField(blank=True, max_length=255, null=True)),
                ('Shipping_city', models.CharField(max_length=255)),
                ('Shipping_zipcode', models.CharField(blank=True, max_length=255, null=True)),
                ('shipping_numberphone', models.CharField(blank=True, max_length=10, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Adresse Livraison',
            },
        ),
    ]
