# Generated by Django 5.1.4 on 2025-01-09 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingadress',
            old_name='Shipping_addresse',
            new_name='shipping_addresse',
        ),
        migrations.RenameField(
            model_name='shippingadress',
            old_name='Shipping_city',
            new_name='shipping_city',
        ),
        migrations.RenameField(
            model_name='shippingadress',
            old_name='Shipping_email',
            new_name='shipping_email',
        ),
        migrations.RenameField(
            model_name='shippingadress',
            old_name='Shipping_full_name',
            new_name='shipping_full_name',
        ),
        migrations.RenameField(
            model_name='shippingadress',
            old_name='Shipping_zipcode',
            new_name='shipping_zipcode',
        ),
    ]
